"""SQLAlchemy ORM models for the Edge (station-local) database.

These models define tables present on the TimescaleDB instance
running locally at each Antarctic research station.
All tables include station_id as a mandatory indexed column.
"""
from __future__ import annotations

import os
import uuid
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Float,
    Index,
    Integer,
    JSON,
    LargeBinary,
    String,
    Text,
    UniqueConstraint,
)

# Use JSONB on PostgreSQL for indexing benefits; fall back to JSON on SQLite
_DB_URL = os.environ.get("DATABASE_URL", "")
if "postgresql" in _DB_URL or "postgres" in _DB_URL:
    from sqlalchemy.dialects.postgresql import JSONB as _JsonType
    from sqlalchemy.dialects.postgresql import UUID as _UuidType
else:
    _JsonType = JSON  # type: ignore[assignment]
    _UuidType = String(36)  # type: ignore[assignment]

from shared.db.base import Base


def _gen_uuid() -> str:
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# Sensor telemetry (TimescaleDB hypertable — see migration)
# ---------------------------------------------------------------------------

class SensorReading(Base):
    """Raw or aggregated sensor reading from a station sensor.

    This table is converted to a TimescaleDB hypertable partitioned by
    timestamp_utc in the Alembic migration. Retention policy: 7 days.
    """
    __tablename__ = "sensor_readings"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    station_id = Column(String(32), nullable=False, index=True)
    sensor_id = Column(String(128), nullable=False, index=True)
    domain = Column(String(32), nullable=False)
    metric_name = Column(String(64), nullable=False)
    value = Column(Float, nullable=False)
    unit = Column(String(32), nullable=False)
    quality = Column(String(32), nullable=False, default="NOMINAL")
    asset_id = Column(String(128), nullable=True)
    timestamp_utc = Column(DateTime(timezone=True), nullable=False, index=True)
    is_aggregate = Column(Boolean, nullable=False, default=False)
    aggregation_window_s = Column(Integer, nullable=True)

    __table_args__ = (
        Index("ix_sensor_readings_station_sensor_time",
              "station_id", "sensor_id", "timestamp_utc"),
    )


# ---------------------------------------------------------------------------
# Alerts
# ---------------------------------------------------------------------------

class Alert(Base):
    """Safety or operational alert generated by the Edge alert engine."""
    __tablename__ = "alerts"

    alert_id = Column(String(128), primary_key=True)
    station_id = Column(String(32), nullable=False, index=True)
    severity = Column(String(16), nullable=False, index=True)
    domain = Column(String(32), nullable=False)
    asset_id = Column(String(128), nullable=True)
    triggered_at = Column(DateTime(timezone=True), nullable=False, index=True)
    description = Column(Text, nullable=False)
    raw_sensor_snapshot = Column(_JsonType, nullable=True)
    ack_state = Column(String(16), nullable=False, default="OPEN", index=True)
    acknowledged_by = Column(String(128), nullable=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    black_box_activated = Column(Boolean, nullable=False, default=False)
    synced_to_cloud = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), nullable=False,
                        default=datetime.utcnow)

    __table_args__ = (
        Index("ix_alerts_station_severity_state",
              "station_id", "severity", "ack_state"),
    )


# ---------------------------------------------------------------------------
# Outbound sync queue
# ---------------------------------------------------------------------------

class OutboundQueueItem(Base):
    """Persistent outbound message queue for the satellite sync agent.

    Items survive Edge service restarts. The sync agent marks items
    acked_by_cloud=True after QoS-confirmed delivery; these are
    periodically purged by a background cleanup job.
    """
    __tablename__ = "outbound_queue"

    queue_id = Column(String(36), primary_key=True, default=_gen_uuid)
    station_id = Column(String(32), nullable=False, index=True)
    message_type = Column(String(64), nullable=False)
    payload_bytes = Column(LargeBinary, nullable=False)
    priority = Column(Integer, nullable=False, default=3, index=True)
    # priority: 0=black_box, 1=critical/high alert, 2=medium/low alert, 3=telemetry
    created_at = Column(DateTime(timezone=True), nullable=False,
                        default=datetime.utcnow)
    attempts = Column(Integer, nullable=False, default=0)
    last_attempted_at = Column(DateTime(timezone=True), nullable=True)
    acked_by_cloud = Column(Boolean, nullable=False, default=False, index=True)
    expires_at = Column(DateTime(timezone=True), nullable=True)
    # Reference to source entity (alert_id, batch_id, event_id, etc.)
    source_id = Column(String(128), nullable=True)

    __table_args__ = (
        Index("ix_outbound_queue_priority_created",
              "priority", "created_at"),
        Index("ix_outbound_queue_pending",
              "acked_by_cloud", "priority", "created_at"),
    )


# ---------------------------------------------------------------------------
# Black-box frames
# ---------------------------------------------------------------------------

class BlackBoxFrame(Base):
    """Tamper-evident, append-only frame from a critical event black-box window.

    The application DB role must have INSERT-only access to this table.
    No UPDATE or DELETE is permitted. Frames are hash-chained via prev_hash.
    """
    __tablename__ = "black_box_frames"

    frame_id = Column(String(36), primary_key=True, default=_gen_uuid)
    event_id = Column(String(128), nullable=False, index=True)
    station_id = Column(String(32), nullable=False, index=True)
    trigger_alert_id = Column(String(128), nullable=False)
    frame_index = Column(Integer, nullable=False)
    readings_protobuf = Column(LargeBinary, nullable=False)  # serialized SensorReading[]
    phase = Column(String(32), nullable=False)  # PRE_EVENT | ACTIVE | POST_RESOLUTION
    prev_hash = Column(LargeBinary(32), nullable=False)
    frame_hash = Column(LargeBinary(32), nullable=False)
    timestamp_utc = Column(DateTime(timezone=True), nullable=False, index=True)
    is_partial_pre_event = Column(Boolean, nullable=False, default=False)
    window_closed = Column(Boolean, nullable=False, default=False)
    synced_to_cloud = Column(Boolean, nullable=False, default=False)

    __table_args__ = (
        UniqueConstraint("event_id", "frame_index", name="uq_blackbox_event_frame"),
        Index("ix_blackbox_event_timestamp", "event_id", "timestamp_utc"),
    )


# ---------------------------------------------------------------------------
# Inventory
# ---------------------------------------------------------------------------

class InventoryItem(Base):
    """Current stock level for a consumable, equipment item, or PPE."""
    __tablename__ = "inventory_items"

    item_id = Column(String(128), primary_key=True)
    station_id = Column(String(32), nullable=False, index=True)
    category = Column(String(32), nullable=False)  # FUEL | SPARE_PARTS | FOOD | MEDICAL
    name = Column(String(256), nullable=False)
    quantity = Column(Float, nullable=False)
    unit = Column(String(32), nullable=False)
    min_safety_threshold = Column(Float, nullable=True)
    daily_burn_rate = Column(Float, nullable=True)       # estimated daily consumption
    days_remaining = Column(Integer, nullable=True)      # quantity / daily_burn_rate
    last_updated = Column(DateTime(timezone=True), nullable=False,
                          default=datetime.utcnow)
    updated_by = Column(String(128), nullable=False, default="system")
    synced_to_cloud = Column(Boolean, nullable=False, default=False)


# ---------------------------------------------------------------------------
# Asset cache (read-only copy of Cloud asset registry at Edge)
# ---------------------------------------------------------------------------

class AssetCache(Base):
    """Local read-only cache of the infrastructure asset registry.

    Populated/updated from Cloud on each successful sync. Used by the
    Edge API and alert engine to resolve asset_id references.
    """
    __tablename__ = "asset_cache"

    asset_id = Column(String(128), primary_key=True)
    station_id = Column(String(32), nullable=False, index=True)
    asset_type = Column(String(64), nullable=False)
    name = Column(String(256), nullable=False)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    elevation_m = Column(Float, nullable=True)
    status = Column(String(32), nullable=False, default="ACTIVE")
    metadata_json = Column(_JsonType, nullable=True)
    last_synced_at = Column(DateTime(timezone=True), nullable=False,
                            default=datetime.utcnow)


# ---------------------------------------------------------------------------
# Audit log (append-only)
# ---------------------------------------------------------------------------

class AuditLogEntry(Base):
    """Append-only audit trail for all write operations at the Edge."""
    __tablename__ = "audit_log"

    entry_id = Column(String(36), primary_key=True, default=_gen_uuid)
    station_id = Column(String(32), nullable=False, index=True)
    actor_id = Column(String(128), nullable=True)  # null for system actions
    actor_role = Column(String(32), nullable=True)
    action = Column(String(64), nullable=False)
    resource_type = Column(String(64), nullable=False)
    resource_id = Column(String(128), nullable=True)
    request_body_hash = Column(String(64), nullable=True)  # SHA-256 hex
    response_status = Column(Integer, nullable=True)
    client_ip = Column(String(64), nullable=True)
    timestamp_utc = Column(DateTime(timezone=True), nullable=False,
                           default=datetime.utcnow, index=True)


# ---------------------------------------------------------------------------
# Link status log
# ---------------------------------------------------------------------------

class LinkStatusRecord(Base):
    """Time-series record of Edge-to-Cloud link state."""
    __tablename__ = "link_status_log"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    station_id = Column(String(32), nullable=False, index=True)
    link_state = Column(String(16), nullable=False)  # UP | DEGRADED | DOWN
    latency_ms = Column(Float, nullable=True)
    packet_loss_pct = Column(Float, nullable=True)
    queue_depth_bytes = Column(BigInteger, nullable=True)
    queue_item_count = Column(Integer, nullable=True)
    recorded_at = Column(DateTime(timezone=True), nullable=False,
                         default=datetime.utcnow, index=True)
