"""Edge local authentication — offline-capable API key validation.

Design rationale:
  The Edge runs at an Antarctic research station that may be completely
  disconnected from the internet for weeks. Therefore, any authentication
  scheme must work fully offline — no token issuing server, no network
  call to verify credentials.

  Solution: Pre-provisioned HMAC-derived API keys per role.
  - Keys are stored in the station config YAML (loaded at startup)
  - Keys are 32-byte hex strings (generated by `make keygen-edge`)
  - Keys are scoped to a role: CREW | OPERATOR | ADMIN
  - No expiry (keys are rotated at each resupply expedition)
  - The Edge never stores user accounts — only pre-shared keys

Key format:   <role>.<hex_secret>
Example:      crew.4a7f2b91e3c0d85a1f6e9b2c4d7e0f3a

Security properties:
  - Constant-time comparison (no timing attack)
  - Role is embedded in the key — no separate lookup needed
  - If a key is compromised, revoke it in the YAML and reload config

Usage:
  Protected endpoints declare:
    require_crew = Depends(LocalAuth(roles=["CREW", "OPERATOR", "ADMIN"]))
    require_admin = Depends(LocalAuth(roles=["ADMIN"]))
"""
from __future__ import annotations

import hashlib
import hmac
import os
from typing import Dict, List, Optional

import structlog
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

log = structlog.get_logger(__name__)

_bearer = HTTPBearer(auto_error=False)

# Role hierarchy: later roles have higher privilege
ROLE_HIERARCHY = ["CREW", "OPERATOR", "ADMIN"]


def _constant_compare(a: str, b: str) -> bool:
    """Timing-safe string comparison."""
    return hmac.compare_digest(a.encode("utf-8"), b.encode("utf-8"))


def parse_key(raw_key: str) -> Optional[tuple[str, str]]:
    """Parse a raw API key into (role, secret).

    Format: <role>.<hex_secret>
    Returns None if malformed.
    """
    parts = raw_key.strip().split(".", 1)
    if len(parts) != 2:
        return None
    role, secret = parts
    if role.upper() not in ROLE_HIERARCHY:
        return None
    return role.upper(), secret


def generate_api_key(role: str, secret_bytes: Optional[bytes] = None) -> str:
    """Generate a new API key for the given role.

    Args:
        role: One of CREW | OPERATOR | ADMIN
        secret_bytes: Optional entropy source (uses os.urandom(32) if None)

    Returns:
        A key string of the form "<role>.<hex_secret>"
    """
    role = role.upper()
    if role not in ROLE_HIERARCHY:
        raise ValueError(f"Unknown role: {role!r}. Must be one of {ROLE_HIERARCHY}")
    secret = secret_bytes if secret_bytes is not None else os.urandom(32)
    return f"{role}.{secret.hex()}"


class KeyStore:
    """In-memory store of valid API keys loaded from station config.

    Keyed by (role, secret_hex) for O(1) lookup and constant-time comparison.
    """

    def __init__(self, raw_keys: List[str]) -> None:
        self._keys: Dict[str, str] = {}  # secret_hex → role
        for raw in raw_keys:
            parsed = parse_key(raw)
            if parsed:
                role, secret = parsed
                self._keys[secret.lower()] = role
                log.info("edge.auth.key_loaded", role=role)
            else:
                log.warning("edge.auth.invalid_key_format", raw=raw[:8] + "…")

    def lookup(self, secret: str) -> Optional[str]:
        """Return the role for a given secret hex, or None if not found."""
        secret = secret.lower()
        # Iterate all keys with constant-time comparison to avoid timing attacks
        found_role: Optional[str] = None
        for stored_secret, role in self._keys.items():
            if _constant_compare(stored_secret, secret):
                found_role = role
        return found_role


# Module-level key store — populated at startup by set_key_store()
_key_store: Optional[KeyStore] = None


def set_key_store(store: KeyStore) -> None:
    global _key_store
    _key_store = store


def get_key_store() -> KeyStore:
    if _key_store is None:
        raise RuntimeError("Edge KeyStore not initialised — call set_key_store()")
    return _key_store


class LocalAuth:
    """FastAPI dependency factory for role-based Edge local auth.

    Usage:
        @router.get("/protected")
        async def protected(principal = Depends(LocalAuth(["CREW", "OPERATOR", "ADMIN"]))):
            ...
    """

    def __init__(self, roles: List[str]) -> None:
        self._allowed_roles = {r.upper() for r in roles}

    async def __call__(
        self,
        credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
    ) -> Dict[str, str]:
        """Validate Bearer token and return principal dict {"role": role}."""
        if credentials is None or not credentials.credentials:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Missing Authorization header. Use: Authorization: Bearer <api_key>",
                headers={"WWW-Authenticate": "Bearer"},
            )

        raw_key = credentials.credentials
        parsed = parse_key(raw_key)
        if parsed is None:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid API key format",
                headers={"WWW-Authenticate": "Bearer"},
            )

        role, secret = parsed
        store = get_key_store()
        stored_role = store.lookup(secret)

        if stored_role is None or stored_role != role:
            log.warning("edge.auth.invalid_key", attempted_role=role)
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid API key",
                headers={"WWW-Authenticate": "Bearer"},
            )

        if role not in self._allowed_roles:
            log.warning("edge.auth.forbidden", role=role, required=self._allowed_roles)
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Role {role!r} is not authorized for this endpoint",
            )

        log.debug("edge.auth.ok", role=role)
        return {"role": role}


# ---------------------------------------------------------------------------
# Convenience dependency aliases
# ---------------------------------------------------------------------------

require_any = LocalAuth(["CREW", "OPERATOR", "ADMIN"])
require_operator = LocalAuth(["OPERATOR", "ADMIN"])
require_admin = LocalAuth(["ADMIN"])
